### ISSUE TITLE
Update gt, gte, lt and lte validators to handle DateTimes compared to the time.Now().UTC()

### ISSUE THREAD

**Issue by joeybloggs** [joeybloggs/go-validate-yourself#11]
There are too many variables to take into account for passing in a time to be validated against or doing anything other than UTC time without creating a custom function for your particular application.

Dates should be stored within the database as UTC, if anyone disagrees they'll have write your own validation function to handle your specific scenario.

**Comment by birdycn** [comment]
how use bro?
